global:
  name: consul
  datacenter: dc1

  tls:
    enabled: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

  gossipEncryption:
    autoGenerate: true

server:
  replicas: 3
  bootstrapExpect: 3

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
